#! /bin/sh
# start_xrd
# Oct 03 2013
# Launch MEDM and set initial values for Xray 
# Use ./start_xrd -e to enter edit mode
# Use with no options to execute immediately
#Modifications:
# 7/29/14 JF Test pulses disabled by default, TEC settings changed, 

source ./set_XRD1_IPADDR

if [ ! -z $1 ]; then
	if [ $1 = "-i" ]; then
		mode="I"	
	elif [ $1 = "-e" ]; then
		mode="E"
	elif [ $1 = "-h" ]; then
		printf "Options:\n -i Interactive startup\n -e Interactive startup with GUI in edit mode\n -h This menu\n"
		exit 1
	else
		printf "**Unknown option\n"
      		exit 1
	fi
fi

if [ "$mode" = "E" ] || [ $mode = "I" ]; then
	printf "Load configuration? (y/n):"
	read conf
else 
	conf="y"
fi

if [ "$conf" = "y" ]; then
	caput det1.EBLK 0
	./test_off             #Test pulse disabled by default
	caput det1.GLDACEN 1
	
	#Set the DAC thresholds.
	caput det1.VL0 0.5
	caput det1.VL1 0.5
	caput det1.VL2 0.5
	caput det1.VH1 2.2
	caput det1.VH2 2.2

	#Set the TEC current.
	#ao3 is Detector TEC. ao5 is ASIC TEC.
	caput det1:ao3 2.25
	caput det1:ao5 1.75

	#Set shaping time to 0.5us
	caput det1.SHPT 0.5us

	#Set low gain.
	caput det1.GAIN L

	#Use internal dead-time calibration
	caput det1.CalibIO Internal

	#Set the Bias to 40v
	caput det1:ao4 40

	caput det1.TP1 .05

	printf "**Configuration loaded\n\n"      
	sleep 1

else
	printf "**Configuration NOT loaded\n\n"
fi
		
if [ "$mode" = "E" ] || [ $mode = "I" ]; then
	printf "Load calibrations? (y/n):"
	read cal
else 
	cal="y"
fi

if [ "$cal" = "y" ]; then
	# CALIBRATIONS
	CAL_DIR=Calibration/XRD_CONFIGURATION

	# Send the DAC calibrations
	bash $CAL_DIR/XRD1-DAC_Config-140708-1454.sh
	# Send the ASIC Trim calibrations
	##bash $CAL_DIR/XRD1-TrimDAC_Config-140729-1522.sh
	##bash $CAL_DIR/XRD1-TrimDAC_Config-140723-1447.sh

	# Send the Pixel calibrations
	bash $CAL_DIR/XRD1-Pix_Config-140729-1522.sh
	## bash $CAL_DIR/XRD1-Pix_Config-140721-1818.sh
	
	printf "**Calibrations loaded\n\n"
else
	printf "**Calibrations NOT loaded\n\n"
fi 

if [ "$mode" = "E" ] || [ $mode = "I" ]; then
	printf "Start GUI? (y/n):"
	read gui
else 
	gui="y"

fi 

if [ "$gui" = "y" ];then

	if [ $mode = "E" ]; then
		medm MEDM_GUI/sydordet.adl &

	else
		medm -x MEDM_GUI/sydordet.adl &			
	fi		
fi
printf "**Startup complete\n"

